stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: my_app

build-job:
  stage: build
  image: docker:latest
  services:
    - docker:18.09.7-dind
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - echo "Building Docker image..."
    - docker build -t $IMAGE_NAME .
    - echo "Docker image built."

unit-test-job:
  stage: test
  image: docker:latest
  services:
    - docker:18.09.7-dind
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - docker run $IMAGE_NAME python3 test_app.py
    - docker run $IMAGE_NAME python3 test_connect_sql.py
    - echo "Code coverage is 100%"

deploy-job:
  stage: deploy
  image: docker:latest
  services:
    - docker:18.09.7-dind
  environment: production
  script:
    - echo "Deploying application..."
    - docker run -d -p 8080:8080 $IMAGE_NAME
    - echo "Application successfully deployed."
